### ISSUE TITLE
Modify "Add Stumbling Block tag" widget in "Edit Student Problem" interface

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-juxtalearn-hub#5]
_Martin - I'm working on this (but I thought I'd put this in your issue tracker - OK?)_

The current interface gives you a list of Stumbling Blocks (SBs) that are associated with the chosen Tricky Topic - you need to delete those that you don't want.

Request: It would be more intuitive if the widget gave you a menu of related SBs and you could select the ones that you wanted. Add/ opt-in as opposed to delete.

Implementation: Check-boxes, probably.

Note:
- Need to provide the existing "Add" Stumbling Block form in the widget, with auto-suggest/ autocomplete;
- SBs that are added to the Student Problem, also need to be attached to the Tricky Topic, apparently.

**Comment by mhawksey** [comment]
Sure

[This line[1] should already add new SBs to parent TT.]

[1] https://github.com/mhawksey/wp-juxtalearn-hub/blob/f65d19ba12bd21cfe456ff357c8fb1bc3754d788/post-types/student_problem.php#L292

**Comment by nfreear** [comment]
Relates to - Bug: https://github.com/IET-OU/oer-evidence-hub-org/issues/12
