### ISSUE TITLE
Add message for missing map/chart in Internet Explorer/ MSIE 7/8

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-juxtalearn-hub#6]
_Martin - I'm working on this.._
- "Unfortunately the map doesn't work in older browsers"
- http://juxtalearn.net/maps-summary-by-country
- http://whatbrowser.org

First commit, 4th March:
- https://github.com/IET-OU/wp-juxtalearn-hub/commit/9467ecde1249685105250ea94249c60670766541

**Comment by mhawksey** [comment]
Both that map and the sankey won't work in IE8 because of no SVG support

**Comment by nfreear** [comment]
Hi Martin,
Yes, I know! I thought it best to at least display a message suggesting that the user upgrades their browser...;)

BTW, [SVG Web](https://code.google.com/p/svgweb/) may be an option, depending on how much we care about MSIE 8 - must check with Gill.

Cheers,

Nick
